### ISSUE TITLE
How to set 'selected'?

### ISSUE THREAD

**Issue by omgo** [monterail/vue-multiselect#138]
client gets options for multiselect from server when page is loading, but I can't set item, it worked on 0.3.1, but didn't work on 1.1.3, could u help me? sorry for my english)

**Comment by shentao** [comment]
Please provide some more details. How does your code look like? Are you sure you’re following the documentation? There were several breaking changes from 0.3.1 and 1.1.3.

**Comment by omgo** [comment]
index.coffee
```
template = require('./index.jade')()

Multiselect = require('vue-multiselect').Multiselect

module.exports =
  name: 'form'
  template: template
  components:
    'app-multiselect': Multiselect
  props:
    model:
      type: Object
  data: ->
    options: [
      text: '2005'
      value: 1
    ,
      text: '2006'
      value: 2
    ,
      text: '2007'
      value: 3
    ]

```


index.jade
```
app-multiselect(v-bind:options="options"
                v-bind:selected.sync="model.year"
                v-bind:multiple="false"
                v-bind:searchable="true"
                v-bind:close-on-select="true"
                v-bind:allow-empty="false"
                placeholder="Начните вводить для поиска"
                deselect-label="Выбрано"
                select-label=""
                selected-label="Выбрано"
                label="text"
                key="value")```

if I understand correctly, it's not working because props are loading after page, and selected doesn't change dynamically, but this code is working on 0.3.1
